buildTests:
   stage: build
   script:
      - make test_geometry
   artifacts:
      paths:
         - test_geometry

test:
   stage: test
   script:
      - test_geometry


staticAnalysis:
   stage: test
   script:
      - make static

style:
  stage: test
  script:
    - make style

coverage:
   stage: test
   script:
      - make coverage
   artifacts:
      paths:
         - coverage
      expire_in: 14 days

memoryLeaks:
   stage: test
   script:
      - make memcheck
   artifacts:
      paths:
         - memcheck.xml
      expire_in: 14 days


docs:
   stage: deploy
   script:
      - make docs
   artifacts:
      paths:
         - docs
      expire_in: 14 days
